---
- name: Configure EC2 server
  hosts: web
  become: true

  tasks:
    - name: Update packages
      yum:
        name: '*'
        state: latest
        use_backend: dnf4

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: true
